### ISSUE TITLE
Green link color hides links

### ISSUE THREAD

**Issue by jablonskidev** [hpyproject/hpyproject.org#15]
While I was researching HPy in order to write about the presentation at the 2021 Python Language Summit, I had some difficulty with your link color:

![Hpy](https://user-images.githubusercontent.com/36643503/119235990-f1189b00-bae9-11eb-871c-34141cf3b9cf.png)

If the target page of a link has been visited, then it is a shade of green that is too similar to black for me to see that there is a link at all. At first, I thought that the link to the blog just hadn't been added yet because there was no black text next to the green link for me to see the contrast.

**Comment by mattip** [comment]
This also affects the pypy.org site since they use the same styling. Probably was a bad choice to make the "visited" color match the green theme.

**Comment by hodgestar** [comment]
@jablonskidev Thank you for reporting this. I've made #16 to address it.
