### ISSUE TITLE
Upgrade to Nikola 8.3.0

### ISSUE THREAD

**Issue by erlend-aasland** [hpyproject/hpyproject.org#47]
Nikola 8.2.2 depends on Yapsy which is incompatible with newer versions of Python. This has been fixed in Nikola 8.3.0. Suggesting to upgrade from Nikola 8.2.2 to Nikola 8.3.0.

**Comment by erlend-aasland** [comment]
Nikola 8.3.0 is not ready yet. Waiting for 8.3.1:

- https://github.com/getnikola/nikola/issues/3736

**Comment by erlend-aasland** [comment]
> Nikola 8.3.0 is not ready yet. Waiting for 8.3.1:
> 
> * [Nikola plugin comand does not work getnikola/nikola#3736](https://github.com/getnikola/nikola/issues/3736)

8.3.1 was released: https://github.com/getnikola/nikola/releases/tag/v8.3.1

**Comment by mattip** [comment]
Thanks for the follow up. Want to submit a PR?
