### ISSUE TITLE
Website search field is malfunctioning

### ISSUE THREAD

**Issue by erlend-aasland** [hpyproject/hpyproject.org#48]
Currently, the search field gives a 404. After a quick look, it seems to try to load a search.html page, which does not exists (AFAICS). I don't know much about the Nikola site-builder, but it seems to me the easiest/fastest solution to get search up and running, is to enable Google or DuckDuckGo search.

**Comment by mattip** [comment]
It used to work. Let's try to get it back before taking drastic measures.

**Comment by mattip** [comment]
Thanks @erlend-aasland for finding this and for the desire for a quick resolution.
