### ISSUE TITLE
Visual regression after gh-50 enabled permalinks for all headers

### ISSUE THREAD

**Issue by erlend-aasland** [hpyproject/hpyproject.org#51]
#50 introduced a visual regression.

After #50:
<img width="468" alt="Screenshot 2024-03-22 at 00 40 21" src="https://github.com/hpyproject/hpyproject.org/assets/13780613/87cca2b8-eaa7-4a56-b4b0-e135d23b10d9">

Before #50:
<img width="450" alt="Screenshot 2024-03-22 at 00 40 43" src="https://github.com/hpyproject/hpyproject.org/assets/13780613/72fc432e-c71a-4c64-bd05-64c03ebf6c4a">

See also:
- https://github.com/hpyproject/hpyproject.org/pull/50#discussion_r1534856787

**Comment by erlend-aasland** [comment]
@hodgestar https://github.com/hpyproject/hpyproject.org/pull/50#discussion_r1534939023:

> Perhaps we can just style them better? Being able to link to subheadings on pages is nice.

**Comment by mattip** [comment]
Thanks for pointing it out. I only did half the sync with the pypy/pypy.org site styling, #52 should make it look better.
